import = [ 
            "~/.config/alacritty/alacritty-titus.toml",
            "~/.config/alacritty/font.toml", 
            "~/.config/alacritty/font-size.toml", 
            "~/.config/alacritty/shared.toml" 
        ]
