# Used by the About.desktop, Activity.desktop, Docker.desktop, Omakub.desktop, and Neovim.desktop apps
import:
  - ~/.config/alacritty/theme.yml
  - ~/.config/alacritty/font.yml
  - ~/.config/alacritty/font-size.yml
  - ~/.config/alacritty/shared.yml

window:
  padding:
    x: 30
    y: 30
