env:
  TERM: xterm-256color

shell:
  program: bash

window:
  title: "Alacritty"
  decorations: none
  blur: true
  opacity: 0.9
  padding:
    x: 10
    y: 10
  dimensions:
    columns: 160
    lines: 80

cursor:
  style:
    shape: Beam
    blinking: Never

colors:
  draw_bold_text_with_bright_colors: true

general:
  live_config_reload: true
  working_directory: None
